stages:
  - test
  - deploy   # Pages vaatii, että Pages-job kuuluu 'deploy'-stageen

# Pylint
pylint:
  stage: test
  script:
    - pip install -r requirements.txt
    - pylint .
  allow_failure: true

# Pages Deployment
pages:
  tags:
    - dind
  stage: deploy
  image: ghcr.io/astral-sh/uv:python3.12-bookworm
  script:
    - uv pip install -r docs/doc-requirements.txt --system
    - uv run --directory "docs" mkdocs build --verbose --site-dir "../public"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  pages: true
