stages:
  - test
  - deploy   # Pages vaatii, että Pages-job kuuluu 'deploy'-stageen

# Pylint with HTML report
pylint:
  tags:
    - dind         # Lisätty tagi, jotta job käynnistyy
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pylint-json2html
    - pylint --output-format=json . > pylint-report.json || true
    - pylint-json2html -f json -o pylint-report.html pylint-report.json
  artifacts:
    paths:
      - pylint-report.html
      - pylint-report.json
    expire_in: 7 days
  allow_failure: true         # ei blokkaa mergeä, mutta raportti syntyy
  rules:
    - if: $CI_COMMIT_BRANCH   # ajetaan kaikilla brancheilla

# Pages Deployment
pages:
  tags:
    - dind
  stage: deploy
  image: ghcr.io/astral-sh/uv:python3.12-bookworm
  script:
    - uv pip install -r docs/doc-requirements.txt --system
    - uv run --directory "docs" mkdocs build --verbose --site-dir "../public"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  pages: true
