version: "3.9"

services:
  mkdocs-prod:
    # Rakentaa imagen projektin juuresta (käyttää Dockerfileä)
    build:
      context: .
      dockerfile: Dockerfile

    # nimi kontille
    container_name: mkdocs-docs

    # Julkaistaan Nginx-portti ulos
    # Jos .env-tiedostossa on MKDOCS_PORT, käytetään sitä, muuten 8080
    ports:
      - "${MKDOCS_PORT:-8080}:80"

    # Käynnistyy automaattisesti uudelleen, ellei pysäytetä käsin
    restart: unless-stopped

    # Aikavyöhyke lokeihin jne.
    environment:
      - TZ=Europe/Helsinki

                   