
site_name: Pingut Projekti 4
site_description: Dokumentaatio (Material for MkDocs -teemalla)
site_author: Sami
site_dir: public

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - toc.integrate
    - search.highlight
    - search.suggest

docs_dir: ./docs

nav:
  - Docs:
      - Esittely: johdanto.md
      - Työnkulku: projektinhallinta.md
      - Teknologiat: tyokalut-ja-teknologia.md
      - Arkkitehtuuri: arkkitehtuuri.md
      - Vaatimusmäärittely: vaatimusmaarittely.md
      - Testaussuunnitelma: testaussuunnitelma.md
      - Rajapintakuvaus:
          - Yleiskuva: rajapintakuvaus.md
          - API-rakenne ja endpointit: api-rakenne-ja-endpointit.md
      - Mikropalvelun käyttöohje: kayttoohje.md
      - Tärkeät linkit: tarkeat-linkit.md
      
plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist
  - attr_list
  - md_in_html